# Generated by Django 3.2.6 on 2025-10-16 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('pago', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
    ]
